DROP DATABASE QUANLYKHACHSAN;
CREATE DATABASE QUANLYKHACHSAN;
USE QUANLYKHACHSAN;
CREATE TABLE PHONG (
	ma_phong INT NOT NULL AUTO_INCREMENT,
	ten_phong VARCHAR(255) DEFAULT '',
	don_gia INT,
	loai_phong CHAR(4) NOT NULL,
	PRIMARY KEY (ma_phong)
);
CREATE TABLE KHACH (
	ma_khach INT NOT NULL AUTO_INCREMENT,
	ten_khach VARCHAR(255) DEFAULT '',
	CCCD CHAR(12),
	dia_chi VARCHAR(255),
	dien_thoai CHAR(10),
	PRIMARY KEY (ma_khach)
);
CREATE TABLE THUEPHONG (
	maHD INT NOT NULL AUTO_INCREMENT,
	ma_khach INT NOT NULL,
	ma_phong INT NOT NULL,
	ngay_den DATE,
	ngay_di DATE,
	so_nguoi INT,
	PRIMARY KEY (maHD),
	FOREIGN KEY (ma_khach) REFERENCES KHACH(ma_khach),
	FOREIGN KEY (ma_phong) REFERENCES PHONG(ma_phong)
);
